name: Code Analysis

on:
    pull_request: null
    push:
        # Prevent duplicating jobs on PR-s from local branches
        branches:
            - "main"

jobs:
    code_analysis:
        strategy:
            fail-fast: false
            matrix:
                actions:
                    -
                        name: 'ECS'
                        run: 'vendor/bin/ecs'

                    -
                        name: 'PHPStan'
                        run: 'vendor/bin/phpstan'

                    -
                        name: 'Unit Tests'
                        run: 'vendor/bin/phpunit'

        name: ${{ matrix.actions.name }}
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1
                    # needed by phpunit
                    extensions: mbstring

            # composer install cache - https://github.com/ramsey/composer-install
            -   uses: "ramsey/composer-install@v2"

            -   run: ${{ matrix.actions.run }}
